ARG RUBY_VERSION=3.2.2
FROM ruby:$RUBY_VERSION-slim as base

WORKDIR /real-estate-app

ENV BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_BIN="/usr/local/bundle/bin"

FROM base as build

RUN apt-get update && apt-get install --no-install-recommends -y \
      build-essential \
      libpq-dev \
      libvips


RUN gem install bundler --no-document

COPY Gemfile Gemfile.lock ./

RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git

COPY . .
RUN chmod +x bin/docker-dev-server.sh

FROM base

RUN apt-get update && apt-get install --no-install-recommends -y \
      postgresql-client

# Copy built artifacts: gems, application
COPY --from=build /usr/local/bundle /usr/local/bundle
COPY --from=build /real-estate-app /real-estate-app/

# Get NodeJS
COPY --from=node:20-slim /usr/local/bin /usr/local/bin