default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>

development:
  <<: *default
  database: real_estate_app_development

test:
  <<: *default
  database: real_estate_app_test

production:
  <<: *default
  database: real_estate_app_production
  username: real_estate_app
  password: <%= ENV['REAL_ESTATE_APP_DATABASE_PASSWORD'] %>
